### ISSUE TITLE
Cannot find module "."

### ISSUE THREAD

**Issue by balthier82** [kutyel/linq.ts#40]
Hi,

when I run `ionic serve` on Windows command prompt, the google chrome developer console throws the following error:

> Cannot find module "." 

in file `<project dir>\node_modules\linqts\dist\linq.js` at line 8.

The content of the `linq.js` file is:

```
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
(function (dependencies, factory) {
    if (typeof module === 'object' && typeof module.exports === 'object') {
        var v = factory(require, exports); if (v !== undefined) module.exports = v;
    }
    else if (typeof define === 'function' && define.amd) {
        define(dependencies, factory);
    }
})(["require", "exports"], function (require, exports) {
    "use strict";
...
```
What can be the problem?

Thanks in advance.

**Comment by kutyel** [comment]
Please try upgrading to v1.7.1 and it should be fixed :wink:

**Comment by balthier82** [comment]
I updated the library to version 1.7.1 but the problem persists.

**Comment by kutyel** [comment]
Can you try the solution provided in https://github.com/kutyel/linq.ts/pull/43#issuecomment-272123019 ? Thanks in advance!

**Comment by kutyel** [comment]
Can someone please confirm that this error is gone with v1.7.3? Thanks in advance! 😉  cc: @balthier82 @Zoxive @abbasmhd @jamesrichford

**Comment by wadenweh** [comment]
Confirm!
Tahnks @kutyel. No errors, nice!
